# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class NLImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RotateImage = channel.unary_unary(
                '/NLImageService/RotateImage',
                request_serializer=image__pb2.NLImageRotateRequest.SerializeToString,
                response_deserializer=image__pb2.NLImage.FromString,
                )
        self.CustomImageEndpoint = channel.unary_unary(
                '/NLImageService/CustomImageEndpoint',
                request_serializer=image__pb2.NLCustomImageEndpointRequest.SerializeToString,
                response_deserializer=image__pb2.NLCustomImageEndpointResponse.FromString,
                )


class NLImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RotateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomImageEndpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RotateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateImage,
                    request_deserializer=image__pb2.NLImageRotateRequest.FromString,
                    response_serializer=image__pb2.NLImage.SerializeToString,
            ),
            'CustomImageEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomImageEndpoint,
                    request_deserializer=image__pb2.NLCustomImageEndpointRequest.FromString,
                    response_serializer=image__pb2.NLCustomImageEndpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NLImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NLImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RotateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NLImageService/RotateImage',
            image__pb2.NLImageRotateRequest.SerializeToString,
            image__pb2.NLImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomImageEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NLImageService/CustomImageEndpoint',
            image__pb2.NLCustomImageEndpointRequest.SerializeToString,
            image__pb2.NLCustomImageEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
